### ISSUE TITLE
Vendégszoba foglaltság jelzése

### ISSUE THREAD

**Issue by csutakbalazs** [tonhal/smartkoli#23]
Vendéget fogadok, saját szobában. A táblázatban helyesen látszik, hogy a foglalás saját szobára történt, ennek ellenére a főoldalon azt írja, hogy a vendégszoba ma éjjel foglalt a vendégeim számára.

Ha jól sejtem, a gond a LandingPageController.php-ben levő lekérdezésben van:
```
$current_guestroom = DB::table('guests')
            ->join('users','users.id','=','guests.user_id')
            ->select('users.name as name')
            ->whereRaw("DATE(arrival) = ?", [$today])
            ->first();

        if($current_guestroom === null) {
            $current_guestroom = False;
        }
```

**Comment by tonhal** [comment]
Megoldva és 1.1.3-as verzióban kijavítva. A szűrőfeltétel hiánya volt a probléma.
